version: 0.6.1

safe: true
markdown: kramdown
highlighter: true
permalink: /:categories/:title

exclude: ["stylobate", "skins/islands/node_modules", "all.styl", "*.sublime-project", "*.sublime-workspace", "node_modules"]

production_url: http://yandex-ui.github.io/stylobate-islands
relative_permalinks: false

# Add a possibility to use full url
github_repo: "yandex-ui/stylobate-islands"

menu:
    - index
    - classnames
    - codestyle
    - skins

link_handles:
    - prefix: "@"
      handle: "https://twitter.com/"
    - prefix: "gh:"
      handle: "https://github.com/"

langs:
    - ru
    - en

default_lang: ru


loc:
    laquo:
        ru: "«"
        en: "“"
    raquo:
        ru: "»"
        en: "”"
